server:
  port: 9000
spring:
  application:
    name: ServiceB
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100
        circuitBreaker:
          requestVolumeThreshold: 4